# This file contains values from Cookiecutter

default_context:
  project_name: "internet-ml"
  project_description: "Internet-ML: Allowing ML to connect to the internet"
  organization: "internet-ml"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.11
  github_name: "internet-ml"
  email: "contact@thamognya.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
